### ISSUE TITLE
Header with tabs: Send, Receive, Earn

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/joinmarket-webui#20]
See the [Main V2](https://www.figma.com/file/kfejZJFlwBywvLEnPEmJo1/JoinMarket-UI?node-id=2850%3A68011) page in Figma:

![Screenshot from 2022-01-26 16-15-34](https://user-images.githubusercontent.com/109058/151192047-269f27e2-d6ea-46c8-a75b-11c00233cc7c.png)

Rough component outline:
- [x] Header component (added in #29)
- [x] Wallet name & balance (added in #29)
- [x] Send / Receive / Earn (added in #29)
- [x] Settings (gear icon) (added in #26)

**Comment by dennisreimann** [comment]
I think it makes sense to have some kind of status indicator next to the Earn link (see current implementation), which can show whether or not the Yield Generator service is currently running.

**Comment by GBKS** [comment]
Here's an idea for an activity indicator. Similar to what you might see in apps or a desktop status bar.

<img width="340" alt="joinmarket-tabs-activity-indicator" src="https://user-images.githubusercontent.com/695901/151380284-b7a1e770-f117-4c25-b462-d070017e4a5c.png">

**Comment by dnlggr** [comment]
Gonna have a look at this now since all issues of the 0.0.3 milestone are already taken and I really like the looks of that header. 😉

**Comment by dennisreimann** [comment]
Just merged the Settings PR, the road is clear. 👍

**Comment by dergigi** [comment]
Gear icon added in #26
