### ISSUE TITLE
List of little annoyances and other stuff

### ISSUE THREAD

**Issue by theborakompanioni** [joinmarket-webui/joinmarket-webui#66]
A small list of things that stood out during testing and trial. 

Please expand it according to your own assessment and let's talk about which are important before the first beta version is released.
Feel free to give an estimated priority as well.

- [x] Inform user about coinjoin state immediately after coinjoin is initiated. Preferably via Websocket ~~Fetch `/session` immediately after starting taker~~ (otherwise user might wait up to 10 seconds to know what is going on) - https://github.com/joinmarket-webui/joinmarket-webui/issues/46
- [x] #83
- [x] #87
- [x] From @AdamISZ : When the maker is started without coins it says "maker cannot start, no coins", but it's important that it should say "no confirmed coins". See https://github.com/joinmarket-webui/joinmarket-webui/issues/34#issuecomment-1032558663 - PR opened https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1190
- [x] #157
- [x] Improve wording of error message when trying to send to an "invalid" address: "Invalid request format." is not meaningful. (400 InvalidRequestFormat on all assertion errors.. see [wallep_rpc.py#L548](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/fd5871bb2d89e96efe344040b4576627e84fc644/jmclient/jmclient/wallet_rpc.py#L548))
- [ ] Prevent user from starting taker with insufficient funds (?):  #155 
  - Might be that a taker operation is started and then aborted - either unconfirmed or too little funds available (takes 60s to be resolved)
- [ ] Balance shown on Send page might not be spendable (e.g. utxo is frozen) https://github.com/joinmarket-webui/joinmarket-webui/issues/78

(This list should not contain missing features (e.g. "display spendable funds" or "ability to sweep"), but rather just document odd behaviour or possible improvements for existing ones.)

**Comment by theborakompanioni** [comment]
> > Fetch `/session` immediately after starting taker (otherwise user might wait up to 10 seconds to know what is going on)
> 
> Comment from @dennisreimann: Might be a good idea to bring back the WebSocket connection, it would contain this information.

Yeah, but I also stated it wrong - should be neutral, I did not want to propose a solution already.. will change to "Inform user about coinjoin state immediately after coinjoin is initiated.". Websocket would be great of course! :+1:

**Comment by dergigi** [comment]
One more thing I noticed, not sure if it's already covered by the above: when "Earn" is active, i.e. the yield generator service is running, the user can't send a transaction as a coinjoin, and vice-versa. Reason: `Service already started.`

**Comment by theborakompanioni** [comment]
All of the items on the list are now either fixed, addressed in a PR or externalized as own issue. Proposing to close this issue.

**Comment by MaxHillebrand** [comment]
Well done fellas.
